### ISSUE TITLE
Github webhook do not run on all merges

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/arewefastyet#148] opened 2021-05-06 05:36 UTC
**Describe the bug**
Github webhooks do not run on all merges on VItess

**Expected behavior**
Github webhooks should run on all merges on VItess

**Comment by frouioui** [comment] 2021-05-07 05:31
The issue was caused by `tf-exec 0.13.0`, and got fixed by merging #143.

**Closed by frouioui** 2021-05-07 05:31 UTC
Labels: Component: Infra, GH Actions, P1
